[
  'Our Universe - Наша вселенная',
  'The World - Мир',
  'The Human Bodu - Человеческое Тело',
  'Clothes 1 - Одежда 1',
  'Clothes 2 - Одежда 2',
  'Clothes 3 - Одежда 3',
  'Clothes 4 - Одежда 4',
  'In Town - В Городе',
  'At The Post Office - На Почте',
  'The Law - Закон, Правопорядок',
  'Fire and Medical Service - Пожарная и педицинская помощь',
  'In School - В Школе',
  'In The Science Laboratory - В Научной Лоборатории',
  'In An Office - В Конторе',
  'In The Supermarket - В Универмаге',
  'In A Workshop - В Мастерской',
  'Tools - Инструменты',
  'On A Building Site - На строительной площадке',
  'A house - Дом',
  'The hall - Прихожая',
  'The sitting-room / living-room - Прихожая',
  'The kitchen - Кухня',
  'The bebdroom / The baby - Спальня, детская',
  'Household objects - Хозяйственные принадлежности',
  'The bathroom and toilet - Ванная комната и туалет',
  'In the country - За городом',
  'By the sea - На море',
  'On the farm - На ферме',
  'Power - Энергия',
  'Travel by road 1 - Путешествие по дороге 1',
  'Travel by road 2 - Путешествие по дороге 2',
  'Travel by road 3 - Путешествие по дороге 3',
  'Travel by train - Путешествие на поезде',
  'Travel by water 1 - Путешествие по воде 1',
  'Travel by water 2 - Путешествие по воде 2',
  'Travel by air. Airport - Путешествие по воздуху. Аэропорт',
  'National Defence - Национальная Оборона',
  'Recreation. 1. Sport - Отдых. 1. Спорт',
  'Recreation. 2. Sport - Отдых. 2. Спорт',
  'Recreation. 3. Music - Отдых. 3. Музыка',
  'Recreation. 4. Bar / Restaurant - Отдых. 4. Бар / Ресторан',
  'Recreation. 5. Hobbies - Отдых. 5. Увлечения',
  'Recreation. 6. Leisure - Отдых. 6. Досуг',
  'Sewing - Шитье',
  'Containers - Емкости',
  'Fruits - Фрукты',
  'Plants - Растения',
  'Fish and other animals - Рыбы и другие животные',
  'Insect - Насекомые',
  'Reptiles - Пресмыкающиеся',
  'Birds - Птицы',
  'Animals - Животные',
  'Occupations, Professions - Профессии',
  'Vrebs - Глаголы',
  'Nouns of quantity - Количества',
  'Adjectives - Определения (Прилагательные)',
  'Lines and shapes - Линии и формы',
  'Measurement - Система мер, измерения',
  'Time, Date, Temperature - Время, число/дата, температура',
  'Family relationship - Родственные отношения',
  'Prepositions - Предлоги',
  'The signs of the Zodiac - Знаки Зодиака',
  'Colours - Цвета',
  'Pronouns, Possesives, Adverbs of place - Местоимения, Наречия',
  'Цифры, Вес, Размеры, Время',
]