[
  'Personal information',
  'Family members I',
  'Family members II',
  'North America',
  'The World',
  'Everyday Activities I',
  'Everyday Activities II',
  'The Classroom',
  'Classroom Actions',
  'Countries, Nationalities and Languages',
  // 'Types of Housing',
  // 'The Living Room',
  // 'The Dining Room',
  // 'The Dining Room: a place setting',
  'The Bedroom',
  // 'The Kitchen',
  // 'The Kitchenware',
  'The Baby\'s Room',
  'Baby Care',
  'The Bathroom',
  'Personal Care Products',
  'Household Cleaning and Laundry',
  'Outside the Home',
  'The Apartment Building',
  'Housing Utilities, Services, and Repairs',
  'Tools',
  'Gardering Tools and Home Supplies',
  'Numbers',
  'Mathematics',
  'Time',
  'The Calendar',
  'Place Around Town I',
  'Place Around Town II',
  'The City',
  'Describing People and Thinks',
  'Describing Physical States and Emotions',
  'Fruits',
  'Vegetables',
  'The Supermarket I',
  'The Supermarket II',
  'Containers and Quantities',
  'Units of Measure',
  'Food Preparation and Recipes',
  'Fast Food and Sandwiches',
  'The Restaurant',
  'Colors',
  'Clothing',
  'Sleepwear, Underwear, and Footwear',
  'Exercise clothing and Outwear',
  'Jewelry and Accessories',
  'Describing Clothing',
  'The Department Store',
  'Video and Audio Equipment',
  'Computers, Telephones, and Cameras',
  'The Toy Store',
  'Money',
  'The Bank',
  'The Body',
  'Ailments, Symptoms, and Injuries',
  'Medical and Dental Care',
  'Medical Treatment and The Hospital',
  'Medicine',
  'The Post Office',
  'The Library',
  'The School',
  'School Subjects and Extracurricular Activities',
  'Occupations I',
  'Occupations II',
  'Work Activities',
  'The Office',
  'Office Equipment',
  'Office Furnishing',
  'Office Supplies',
  'The Factory',
  'The Construction Site',
  'The Car',
  'Highways and Streets',
  'Public Transportation',
  'The Airport',
  'The Airplane',
  'The Weather and Seasons',
  'Outdoor Recreation',
  'The Park and The Playground',
  'The Beach',
  'Individual Sports and Recreation',
  'Team Sports',
  'Team Sports Equipment',
  'Winter Sports and Rrecreation',
  'Water Sports and Rrecreation',
  'Sport and Exercise Actions',
  'Handicrafts, Hobbies, and Game',
  'Entertainment',
  'Types of Entertainment',
  'Musical Instruments',
  'Trees, Flowers, and Plants',
  'The Environment and Energy',
  'The Farm and Farm Animals',
  'Animals and Pets',
  'Birds and Insects',
  'Fish, Sea Animals, and Reptiles',
  'Measurements and Geometric Shapes',
  'The Universe and Space Exploration',
]